language: rust
rust:
  - stable
matrix:
  allow_features:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
sudo: required
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  sudo pip install --upgrade pip &&
  sudo pip install ghp-import2 &&
  ghp-import -n target/doc &&
  git push -qf https://${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages